[package]
name = "snp_report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sev = "1.1.0"
sev-snp-utils = "1.3.3"
